### ISSUE TITLE
native build error

### ISSUE THREAD

**Issue by tanggen** [jonashackt/spring-boot-graalvm#31]
when i build a springboot project ,i got error:
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.boot.logging.java.JavaLoggingSystem$Factory was unintentionally initialized at build time. org.springframework.boot.SpringBootFactories caused initialization of this class with the following trace:
        at org.springframework.boot.logging.java.JavaLoggingSystem$Factory.<clinit>(JavaLoggingSystem.java:190)
        at org.springframework.boot.SpringBootFactories.<clinit>(SpringBootFactories.java:99)

-------------------------------------------------------------------------
native-image.cmd --version
GraalVM Version 20.3.0 (Java Version 11.0.9+7-LTS-jvmci-20.3-b06)

**Comment by jonashackt** [comment]
Did the upgrade to GraalVM 20.3.x yesterday with https://github.com/jonashackt/spring-boot-graalvm/issues/21 - so maybe give it a try again @tanggen - or file a question on stackoverflow
