### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [jonashackt/spring-boot-graalvm#51]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by jonashackt** [comment]
Here's a full post about the why https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/
